# Generated by Django 5.2.9 on 2026-02-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_program_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInquiry',
        ),
    ]
