# Generated by Django 5.2.9 on 2026-02-18 02:26

import re
from html import escape

from django.utils.html import strip_tags
from django.db import migrations, models


HTML_TAG_PATTERN = re.compile(r"<[a-zA-Z!/][^>]*>")
BLOCK_BREAK_PATTERN = re.compile(
    r"</(li|p|div|h[1-6]|tr|td|th|blockquote)>|<br\s*/?>",
    flags=re.IGNORECASE,
)


def _build_html_from_items(items: list[str]) -> str:
    clean_items = [str(item).strip() for item in (items or []) if str(item).strip()]
    if not clean_items:
        return ""
    list_items = "".join(f"<li>{escape(item)}</li>" for item in clean_items)
    return f"<ul>{list_items}</ul>"


def _items_from_text(raw_text: str) -> list[str]:
    html = str(raw_text or "")
    text = strip_tags(BLOCK_BREAK_PATTERN.sub("\n", html))
    return [line.strip() for line in text.splitlines() if line.strip()]


def _normalize_legacy_outcomes(raw_value) -> tuple[list[str], str]:
    if isinstance(raw_value, dict):
        html = str(raw_value.get("html") or "").strip()
        raw_items = raw_value.get("items") or []
        items = [str(item).strip() for item in raw_items if str(item).strip()]
        if html:
            parsed_items = _items_from_text(html)
            if parsed_items:
                items = parsed_items
            return items, html
        return items, _build_html_from_items(items)

    if isinstance(raw_value, list):
        items = [str(item).strip() for item in raw_value if str(item).strip()]
        return items, _build_html_from_items(items)

    if isinstance(raw_value, str):
        raw = raw_value.strip()
        if not raw:
            return [], ""
        if HTML_TAG_PATTERN.search(raw):
            return _items_from_text(raw), raw
        items = [line.strip() for line in raw.splitlines() if line.strip()]
        return items, _build_html_from_items(items)

    return [], ""


def backfill_program_learning_outcomes(apps, schema_editor):
    Program = apps.get_model("core", "Program")

    for program in Program.objects.all().iterator():
        items, html = _normalize_legacy_outcomes(getattr(program, "what_you_learn", None))
        program.what_you_learn_items = items
        program.what_you_learn_html = html
        program.save(update_fields=["what_you_learn_items", "what_you_learn_html"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_program_learning_controls_and_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='what_you_learn_html',
            field=models.TextField(blank=True, default='', help_text='Rich text learning outcomes HTML'),
        ),
        migrations.AddField(
            model_name='program',
            name='what_you_learn_items',
            field=models.JSONField(blank=True, default=list, help_text='Derived plain-text learning outcomes'),
        ),
        migrations.RunPython(backfill_program_learning_outcomes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='program',
            name='what_you_learn',
        ),
    ]
