# Generated by Django 5.2.14 on 2026-07-13 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_wishlistitem'),
        ('core', '0024_program_review_defaults'),
        ('progression', '0007_enrollment_access_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOnboardingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors')], default='draft', max_length=32)),
                ('selection_mode', models.CharField(choices=[('ids', 'Selected applications'), ('filters', 'All matching filters')], max_length=16)),
                ('selection_filters', models.JSONField(blank=True, default=dict)),
                ('excluded_ids', models.JSONField(blank=True, default=list)),
                ('preview_counts', models.JSONField(blank=True, default=dict)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('email_failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_onboarding_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_onboarding_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionOnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('outcome', models.CharField(blank=True, default='', max_length=64)),
                ('account_state', models.CharField(blank=True, default='', max_length=24)),
                ('email_status', models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_sent', max_length=16)),
                ('email_attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_items', to='core.admissionapplication')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.admissiononboardingbatch')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_onboarding_items', to='progression.enrollment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_onboarding_items', to='commerce.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_onboarding_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_onboarding_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='admissiononboardingbatch',
            index=models.Index(fields=['status', '-created_at'], name='admission_o_status_283f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiononboardingbatch',
            index=models.Index(fields=['created_by', '-created_at'], name='admission_o_created_0f8b68_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiononboardingitem',
            index=models.Index(fields=['batch', 'status'], name='admission_o_batch_i_e8e0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiononboardingitem',
            index=models.Index(fields=['batch', 'email_status'], name='admission_o_batch_i_54a4fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissiononboardingitem',
            constraint=models.UniqueConstraint(fields=('batch', 'application'), name='unique_onboarding_batch_application'),
        ),
    ]
