# Generated by Django 5.2.9 on 2026-02-02 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_rename_assessments_rubrics_scope_owner_idx_assessments_scope_79e54f_idx_and_more'),
        ('core', '0011_remove_contact_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankentry',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_question_banks', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(help_text='Questions in this bank are shared within the program', on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='core.program')),
            ],
            options={
                'db_table': 'question_banks',
            },
        ),
        migrations.AddField(
            model_name='questionbankentry',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Optional grouping for questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='assessments.questionbank'),
        ),
        migrations.AddIndex(
            model_name='questionbankentry',
            index=models.Index(fields=['bank'], name='question_ba_bank_id_98083c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankentry',
            index=models.Index(fields=['category'], name='question_ba_categor_c0017d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['program'], name='question_ba_program_e07972_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['owner'], name='question_ba_owner_i_3c9eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['category'], name='question_ba_categor_d25ca2_idx'),
        ),
    ]
