# Generated by Django 5.2.9 on 2026-02-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_questionbankentry_category_questionbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbankentry',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Optional grouping for questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='assessments.questionbank'),
        ),
    ]
