# Generated by Django 5.2.9 on 2026-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_questionbankentry_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_retake_after_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_style',
            field=models.CharField(choices=[('default', 'Default'), ('pagination', 'Pagination'), ('global', 'Global')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_attempt_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_points_override',
            field=models.PositiveIntegerField(blank=True, help_text='If set, quiz score is scaled to this value instead of sum of question points', null=True),
        ),
    ]
