# Generated by Django 5.2.9 on 2026-02-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_quiz_extended_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Percentage weight in final grade (0-100). Quizzes + Assignments should sum to 100%.'),
        ),
    ]
