# Generated by Django 5.2.9 on 2026-02-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_quiz_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multi', 'Multiple Choice (Multi-Select)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('matching', 'Matching'), ('image_matching', 'Image Matching'), ('fill_blank', 'Fill in the Blank'), ('ordering', 'Ordering/Sequence')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionImageMatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, default='')),
                ('question_image', models.CharField(blank=True, default='', max_length=500)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_image', models.CharField(blank=True, default='', max_length=500)),
                ('explanation', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_matching_pairs', to='assessments.question')),
            ],
            options={
                'db_table': 'question_image_matching_pairs',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['question', 'position'], name='question_im_questio_adbfb1_idx')],
            },
        ),
    ]
