# Generated by Django 5.2.9 on 2026-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allow_retake_after_pass',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_style',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_attempt_history',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_unit',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_points_override',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multi', 'Multiple Choice (Multi-Select)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank'), ('ordering', 'Ordering/Sequence')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Percentage weight in final grade'),
        ),
    ]
