# Generated by Django 5.2.9 on 2026-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_quizattempt_runtime_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionimagematchingpair',
            name='question_im_questio_adbfb1_idx',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('mcq_multi', 'Multiple Choice (Multi-Select)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('matching', 'Matching'), ('image_matching', 'Image Matching'), ('fill_blank', 'Fill in the Blank'), ('ordering', 'Ordering/Sequence')], max_length=20),
        ),
    ]
