# Generated by Codex on 2026-03-06

from html import unescape

from django.db import migrations
from django.utils.html import strip_tags


def normalize_text(value):
    decoded = unescape(str(value or "")).replace("\xa0", " ")
    return " ".join(strip_tags(decoded).split())


def normalize_text_list(values):
    if not isinstance(values, list):
        return []

    normalized = []
    for value in values:
        cleaned = normalize_text(value)
        if cleaned:
            normalized.append(cleaned)
    return normalized


def normalize_text_mapping(values):
    if not isinstance(values, dict):
        return {}

    normalized = {}
    for key, value in values.items():
        cleaned = normalize_text(value)
        if cleaned:
            normalized[str(key)] = cleaned
    return normalized


def normalize_question_answer_data(question_type, answer_data):
    if not isinstance(answer_data, dict):
        return {}

    normalized = dict(answer_data)
    normalized_type = str(question_type or "").strip().lower()

    if normalized_type in {"mcq", "mcq_multi"}:
        normalized["options"] = normalize_text_list(normalized.get("options", []))

    if normalized_type == "short_answer":
        normalized["keywords"] = normalize_text_list(normalized.get("keywords", []))

    if normalized_type == "ordering":
        normalized["items"] = normalize_text_list(normalized.get("items", []))
        normalized["explanations"] = normalize_text_mapping(
            normalized.get("explanations", {})
        )

    return normalized


def forwards(apps, schema_editor):
    Question = apps.get_model("assessments", "Question")
    QuestionOption = apps.get_model("assessments", "QuestionOption")
    QuestionMatchingPair = apps.get_model("assessments", "QuestionMatchingPair")
    QuestionImageMatchingPair = apps.get_model(
        "assessments", "QuestionImageMatchingPair"
    )
    QuestionGapAnswer = apps.get_model("assessments", "QuestionGapAnswer")

    for question in Question.objects.all().iterator():
        normalized_text = normalize_text(question.text)
        normalized_answer_data = normalize_question_answer_data(
            question.question_type,
            question.answer_data,
        )
        update_fields = []
        if normalized_text != question.text:
            question.text = normalized_text
            update_fields.append("text")
        if normalized_answer_data != question.answer_data:
            question.answer_data = normalized_answer_data
            update_fields.append("answer_data")
        if update_fields:
            question.save(update_fields=update_fields)

    for option in QuestionOption.objects.all().iterator():
        normalized = normalize_text(option.text)
        if normalized != option.text:
            option.text = normalized
            option.save(update_fields=["text"])

    for pair in QuestionMatchingPair.objects.all().iterator():
        normalized_left = normalize_text(pair.left_text)
        normalized_right = normalize_text(pair.right_text)
        normalized_explanation = normalize_text(pair.explanation)
        update_fields = []
        if normalized_left != pair.left_text:
            pair.left_text = normalized_left
            update_fields.append("left_text")
        if normalized_right != pair.right_text:
            pair.right_text = normalized_right
            update_fields.append("right_text")
        if normalized_explanation != pair.explanation:
            pair.explanation = normalized_explanation
            update_fields.append("explanation")
        if update_fields:
            pair.save(update_fields=update_fields)

    for pair in QuestionImageMatchingPair.objects.all().iterator():
        normalized_question = normalize_text(pair.question_text)
        normalized_answer = normalize_text(pair.answer_text)
        normalized_explanation = normalize_text(pair.explanation)
        update_fields = []
        if normalized_question != pair.question_text:
            pair.question_text = normalized_question
            update_fields.append("question_text")
        if normalized_answer != pair.answer_text:
            pair.answer_text = normalized_answer
            update_fields.append("answer_text")
        if normalized_explanation != pair.explanation:
            pair.explanation = normalized_explanation
            update_fields.append("explanation")
        if update_fields:
            pair.save(update_fields=update_fields)

    for gap in QuestionGapAnswer.objects.all().iterator():
        normalized_answers = normalize_text_list(gap.accepted_answers)
        normalized_explanation = normalize_text(gap.explanation)
        update_fields = []
        if normalized_answers != gap.accepted_answers:
            gap.accepted_answers = normalized_answers
            update_fields.append("accepted_answers")
        if normalized_explanation != gap.explanation:
            gap.explanation = normalized_explanation
            update_fields.append("explanation")
        if update_fields:
            gap.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0015_remove_questionimagematchingpair_question_im_questio_adbfb1_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
