# Generated by Django 5.2.9 on 2026-02-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_user_id_17dbdf_idx',
            old_name='orders_user_status_665f31_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_program_0dcab9_idx',
            old_name='orders_progra_77c782_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_provide_f4f05f_idx',
            old_name='orders_provi_433fd0_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentattempt',
            new_name='payment_att_order_i_e038e8_idx',
            old_name='payment_att_order_i_e5c548_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentattempt',
            new_name='payment_att_provide_5013ed_idx',
            old_name='payment_att_provide_dfbfa6_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='payment_web_provide_bcd2a3_idx',
            old_name='payment_web_provider_9192bf_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='payment_web_provide_5a81c4_idx',
            old_name='payment_web_provider_4ab30c_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='payment_web_process_da3ed2_idx',
            old_name='payment_web_processed_38ab71_idx',
        ),
    ]
