# Generated by Django 5.2.9 on 2026-02-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='programreview',
            new_name='program_rev_program_edbae3_idx',
            old_name='program_revi_program_513d98_idx',
        ),
        migrations.RenameIndex(
            model_name='programreview',
            new_name='program_rev_status_0d272b_idx',
            old_name='program_revi_status_7df8e9_idx',
        ),
    ]
