# Generated by Django 5.2.9 on 2026-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment_confirmed', 'Enrollment Confirmed'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('discussion_comment', 'Lesson Discussion Comment'), ('discussion_reply', 'Lesson Discussion Reply'), ('grade_published', 'Grade Published'), ('assignment_graded', 'Assignment Graded'), ('quiz_graded', 'Quiz Graded'), ('announcement', 'New Announcement'), ('instructor_approved', 'Instructor Approved'), ('instructor_rejected', 'Instructor Rejected'), ('program_approved', 'Program Approved'), ('program_changes_requested', 'Program Changes Requested'), ('system', 'System Notification')], max_length=50),
        ),
    ]
