# Generated by Django 5.2.13 on 2026-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment_confirmed', 'Enrollment Confirmed'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('discussion_comment', 'Lesson Discussion Comment'), ('discussion_reply', 'Lesson Discussion Reply'), ('grade_published', 'Grade Published'), ('assignment_graded', 'Assignment Graded'), ('quiz_graded', 'Quiz Graded'), ('announcement', 'New Announcement'), ('direct_message', 'Direct Message'), ('instructor_approved', 'Instructor Approved'), ('instructor_rejected', 'Instructor Rejected'), ('program_approved', 'Program Approved'), ('program_changes_requested', 'Program Changes Requested'), ('system', 'System Notification')], max_length=50),
        ),
    ]
